# Generated by Django 4.2 on 2023-04-16 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'name']},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
