# Generated by Django 4.2 on 2023-06-05 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_email_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id_films', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id_gender', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id_likes', models.AutoField(primary_key=True, serialize=False)),
                ('films', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.films')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
